using UnityEngine;

public enum CardBehaviourEnum
{
    HEAL,
    HEAL_NEIGHBOUR,
    DAMAGE,
    DAMAGE_NEIGHBOUR,
    DAMAGE_OVERTIME,
    FREEZE,
    FREEZE_FUNCTION,
    FREEZE_PLAYER,
    PROTECT, 
    PROTECT_NEIGHBOUR,
    DUPLICATE,
    STEAL,
    PRODUCTION_GOLD,
    MULTIPLY_PRODUCTION,
    MOVE, 
    STEAL_ALL_CARDS,
    DESTROY_ALL_CARDS,
    
    REVIVE,
    ABSORB,
    RELENTLESS
}
